# Generated by Django 5.2.5 on 2025-09-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.TextField(default='no snippet'),
        ),
    ]
