# Generated by Django 5.2.5 on 2025-09-05 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.CharField(default='no-uuid', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(default='no title', max_length=200)),
                ('description', models.TextField(default='no description')),
                ('keywords', models.TextField(default='no keywords')),
                ('snippet', models.TextField(default='no snippet')),
                ('url', models.URLField(default='https://www.google.com')),
                ('language', models.CharField(default='en', max_length=50)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='unknown', max_length=200)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('locale', models.CharField(default='us', max_length=50)),
            ],
        ),
    ]
