# Generated by Django 5.2.5 on 2025-09-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
